version: "3.0"

services:
  terraform:
    build: ./
    volumes:
      - "${HOME}/.aws/credentials:/credentials"
      - "./:/tlp:ro"
      - "${PWD}/:/local"
      - "${HOME}/.tlp-cluster/:/user/"

    working_dir: "/local"

  pssh:
    build:
      dockerfile: DockerfileSSH
      context: "."
    volumes:
      - "${HOME}/.ssh:/root/.ssh:ro"
      - "${PWD}:/local"
      - "./:/tlp:ro"
    working_dir: "/local"

  build-cassandra:
    build:
      dockerfile: DockerfileCassandra
      context: "."
    volumes:
      # fix this before merging to master
      - "${CASSANDRA_DIR}:/cassandra"
      - "${HOME}/.tlp-cluster/builds/${BUILD_NAME}:/builds"
      - "${HOME}/.tlp-cluster/maven-cache/:/root/.m2/"

    environment:
      - BUILD_NAME

  docs:
    image: asciidoctor/docker-asciidoctor

    volumes:
    - ./manual:/documents
    - ./docs:/html

    command: asciidoctor -o /html/index.html  index.adoc

