# Docker compose for testing the monitoring dashboards and prometheus configs
# start with docker-compose -f docker-compose-monitoring-dev.yml up
# that's it.

version: "3.0"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./src/test/resources/monitoring-environment/prometheus.yml:/etc/prometheus/prometheus.yml:ro"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "./src/test/resources/monitoring-environment/grafana.ini:/etc/grafana/grafana.ini:ro"
      - "./src/test/resources/monitoring-environment/provisioning/:/etc/grafana/provisioning/"
      - "./src/main/resources/com/thelastpickle/tlpcluster/commands/origin/provisioning/monitoring/config/grafana/dashboards:/var/lib/grafana/dashboards:ro"

  cassandra:
    image: cassandra:3.11.4
    ports:
      - "9500:9500"
    volumes:
      - "./src/main/resources/com/thelastpickle/tlpcluster/commands/origin/provisioning/cassandra/jmx_prometheus_javaagent-0.12.0.jar.txt:/usr/share/jmx_prometheus_javaagent-0.12.0.jar:ro"
      - "./src/main/resources/com/thelastpickle/tlpcluster/commands/origin/provisioning/cassandra/config.yaml:/usr/share/config.yaml:ro"
    environment:
      JVM_EXTRA_OPTS: '-javaagent:/usr/share/jmx_prometheus_javaagent-0.12.0.jar=9500:/usr/share/config.yaml'
