version: "3.0"

services:
 docs:
    image: asciidoctor/docker-asciidoctor

    volumes:
    - ./manual:/documents
    - ./docs:/html

    command: asciidoctor -o /html/index.html  index.adoc -a TLP_CLUSTER_VERSION=${TLP_CLUSTER_VERSION}
