version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - run: sudo apt-key fingerprint 0EBFCD88
      - run: |
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

      - run: sudo apt-get update
      - run: sudo apt-get install docker-ce docker-ce-cli containerd.io
      - checkout
      - run: ./gradlew test